<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-PrintConnect_Web-6cfededb-b2df-4c02-9ef7-c5ddb42db4bb</UserSecretsId>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <None Update="Data/app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
        <ProjectReference Include="../PrintConnect.Domain/PrintConnect.Domain.csproj" />
        <ProjectReference Include="..\PrintConnect.Adapter\PrintConnect.Adapter.csproj" />
        <ProjectReference Include="..\PrintConnect.Application\PrintConnect.Application.csproj" />
        <ProjectReference Include="..\PrintConnect.Client\PrintConnect.Client.csproj" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8"/>
        <ProjectReference Include="..\PrintConnect.Data.Postgres\PrintConnect.Data.Postgres.csproj" />
        <ProjectReference Include="..\PrintConnect.Data\PrintConnect.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="../../.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="PrintConnect.Web\obj\PrintConnect.Web.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="PrintConnect.Web\obj\project.assets.json" />
    </ItemGroup>

</Project>
